on:
  workflow_call:
    inputs:
      baseDir:
        type: string
        required: true
      runner:
        type: string
        required: true
      scenarioDir:
        type: string
        required: true
      scenarioName:
        type: string
        required: true
      gateway: 
        type: string
        required: true
      vu: 
        type: number
        required: true
      time: 
        type: string
        required: true
      cpuLimit: 
        type: string
        required: true
      memoryLimit: 
        type: string
        required: true
      subgraphDelayRange: 
        type: string
        default: ""

jobs:
  test:
    runs-on: ${{ startsWith(inputs.runner, '{') && fromJSON(inputs.runner) || inputs.runner }}
    name: ${{ inputs.gateway }}
    steps:
      - name: adjust os 
        run: |
          ulimit -n 10000

      - name: checkout
        uses: actions/checkout@v4
        
      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6=0.46.0

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare containers and run benchmark (${{ inputs.time }})
        timeout-minutes: 20
        working-directory: ${{ inputs.baseDir }}/scenarios/${{ inputs.scenarioDir }} 
        run: ./run.sh ${{ inputs.gateway }}
        env:
          ACCOUNTS_SUBGRAPH_DELAY_MS: ${{ inputs.subgraphDelayRange }}
          INVENTORY_SUBGRAPH_DELAY_MS: ${{ inputs.subgraphDelayRange }}
          PRODUCTS_SUBGRAPH_DELAY_MS: ${{ inputs.subgraphDelayRange }}
          REVIEWS_SUBGRAPH_DELAY_MS: ${{ inputs.subgraphDelayRange }}
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}/
          DOCKER_TAG: ":${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
          BENCH_VUS: ${{ inputs.vu }}
          BENCH_OVER_TIME: ${{ inputs.time }}
          MEM_LIMIT: ${{ inputs.memoryLimit }}
          CPU_LIMIT: ${{ inputs.cpuLimit }}

      - uses: actions/upload-artifact@v3
        if: always()
        with: 
          name: ${{ inputs.baseDir }}_${{ inputs.scenarioName }}_${{ inputs.gateway }}
          path: |
            ${{ inputs.baseDir }}/gateways/${{ inputs.gateway }}/k6_summary.json
            ${{ inputs.baseDir }}/gateways/${{ inputs.gateway }}/k6_summary.txt
            ${{ inputs.baseDir }}/gateways/${{ inputs.gateway }}/gateway_log.txt
            ${{ inputs.baseDir }}/gateways/${{ inputs.gateway }}/*.png