name: 'Images Cleanup'

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  report:
    runs-on: ubuntu-latest
    name: report
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6

      # run script with 30m timeout
      - name: cleanup images
        env:
          CF_IMAGES_LINK: ${{ secrets.CF_IMAGES_LINK }}
          CF_IMAGES_TOKEN: ${{ secrets.CF_IMAGES_TOKEN }}
        run: node --experimental-strip-types ./scripts/images-cleanup.ts
        timeout-minutes: 30

